import Image from "next/image";
import Link from "next/link";
import {Art,Button,Title,CTA} from "@/components/UI";
import {pillars,services,projects,insights,faqs} from "@/lib/content";
export const metadata={alternates:{canonical:"/"}};
export default function Home(){return <>
<section className="hero dark"><Image src="/images/hero-home.webp" alt="A luminous neural sphere woven from cyan and indigo light" fill priority sizes="100vw"/><div className="container hero-content"><span className="eyebrow"><i/> HUMAN-AUGMENTED INTELLIGENCE</span><h1>Learn AI.<br/>Apply AI.<br/><em>Amplify</em><br/>Human Potential.</h1><p>I help people and businesses thrive in the age of AI. Practical ideas. Digital experiences. Possibilities with a human purpose.</p><div className="actions"><Button>Book a Free Discovery Call</Button><Button href="/portfolio" secondary>Explore My Work</Button></div><div className="hero-note">AI & DIGITAL SOLUTIONS <span>·</span> COACHING & MENTORSHIP</div></div><div className="hero-bottom container"><span>Technology moves fast. Let’s move with purpose.</span><a href="#belief">SCROLL TO EXPLORE ↓</a></div></section>
<section className="audience-strip"><div className="container"><span>BUILT AROUND YOU</span><p>Students <b>✦</b> Business owners <b>✦</b> Freelancers <b>✦</b> Self-employed <b>✦</b> Job seekers</p></div></section>
<section id="belief" className="section"><div className="container split belief"><div><span className="eyebrow">01 / THE BELIEF</span><h2>The future isn’t<br/>Human vs. AI.<br/><em>It’s Human + AI.</em></h2></div><div><p className="large">Technology can amplify our capabilities. Our creativity, judgment, empathy and purpose make them matter.</p><p>I call this Human-Augmented Intelligence. My work brings practical AI, business growth and human potential into the same conversation.</p><Link className="text-link" href="/about">Get to know me ↗</Link></div></div><div className="container belief-art"><Art name="belief-section-bg" alt="Two luminous trails merging into one flowing gesture"/></div></section>
<section className="section tint"><div className="container"><Title eyebrow="02 / WHAT I DO" title="A little more capable. A lot more possible." text="Four connected ways to turn emerging technology into meaningful progress."/><div className="grid pillar-grid">{pillars.map((p,i)=><Link className="pillar card" key={p.title} href={`/focus#${p.anchor}`}><Art name={p.image} alt={p.title}/><div className="card-body"><span className="eyebrow">0{i+1} ↗</span><h3>{p.title}</h3><p>{p.text}</p></div></Link>)}</div></div></section>
<section className="section"><div className="container"><div className="section-row"><Title eyebrow="03 / WAYS WE CAN WORK TOGETHER" title="Your next step, made practical."/><Link className="text-link" href="/connect">Find your starting point ↗</Link></div><div className="offering-rail">{services.map(s=><Link href="/connect" className="offering card" key={s.title}><Art name={s.image} alt={s.title}/><div className="card-body"><h3>{s.title}</h3><p>{s.text}</p><span className="text-link">Let’s explore ↗</span></div></Link>)}</div></div></section>
<section className="section dark"><div className="container"><div className="section-row"><Title eyebrow="04 / POSSIBILITY IN PRACTICE" title="Ideas, ready to take shape." text="Illustrative concepts showing the kinds of problems we can explore together. Verified project details will be added as available."/><Button href="/portfolio" secondary>Explore the portfolio</Button></div><div className="grid work-grid">{projects.slice(0,3).map(p=><Link href="/portfolio" className="work-card" key={p.title}><Art name={p.image} alt={p.text}/><small>{p.label}</small><h3>{p.title} ↗</h3><p>{p.text}</p></Link>)}</div></div></section>
<section className="section"><div className="container split"><div><Art name="portrait-vihaan-hero" alt="AI-generated illustrative studio portrait; not a verified likeness of Vihaan" portrait/><small className="caption">[Illustrative AI portrait · replace with an approved photo of Vihaan]</small></div><div><span className="eyebrow">THE PERSON BEHIND THE POSSIBILITIES</span><h2>Hi, I’m Vihaan.<br/>Always learning.<br/><em>Always building.</em></h2><p>My mission is to make AI more human, practical and accessible—and help people use it not just to do more, but to become more capable.</p><p>From a first AI workflow to a new digital product, I help turn curiosity into a useful next step.</p><Button href="/about">My story & philosophy</Button></div></div></section>
<section className="section tint"><div className="container"><div className="section-row"><Title eyebrow="05 / NOTES FROM THE JOURNEY" title="Ideas worth spending time with."/><Link className="text-link" href="/insights">All insights ↗</Link></div><div className="grid work-grid">{insights.slice(0,3).map(i=><Link className="card" key={i.title} href="/insights"><Art name={i.image} alt={i.text}/><div className="card-body"><span className="eyebrow">{i.category} · {i.label}</span><h3>{i.title}</h3><p>{i.text}</p><span className="text-link">Read the insight ↗</span></div></Link>)}</div></div></section>
<section className="section"><div className="container split"><Title eyebrow="A LITTLE CLARITY" title="Good questions. Honest answers." text="You don’t need a finished plan to start a conversation."/><div>{faqs.map(([q,a])=><details className="faq" key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></div></section><div className="trust-strip container"><p>Follow the journey <a href="https://instagram.com/reachvihaan">@reachvihaan ↗</a></p><small>[Certifications to confirm] · [Learner testimonials to confirm] · [Audience counts to confirm]</small></div><CTA/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"FAQPage",mainEntity:faqs.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))})}}/></>}
