import type {Metadata} from "next";
import {Hero,Section} from "@/components/Verse";
import {Title,Art,Button,CTA} from "@/components/UI";
import {Gallery} from "@/components/Gallery";
import {LeadForm} from "@/components/Explore";
import {insights} from "@/lib/content";
import {whatsapp} from "@/lib/whatsapp";
export const metadata:Metadata={title:"Books & Insights",description:"Practical reading on AI, careers, entrepreneurship, student learning and human potential.",alternates:{canonical:"/books-insights"}};
export default function Page(){return <><Hero label="BOOKS & INSIGHTS" title="Ideas to explore. Knowledge to use." text="Read with curiosity. Return with a fresh perspective. Discover practical learning across AI, work, business and everyday life." image="books-ebooks-cover-set"/><Section id="explore"><div id="books"><Title eyebrow="THE READING SHELF" title="A world of ideas, within reach." text="[Book titles, previews, formats and publication dates to confirm]. These categories represent the planned publishing collection."/><div className="grid cards-grid">{["AI & Technology","Career & Professional Growth","Entrepreneurship & Business","Student Learning","Personal Growth & Wellbeing"].map(n=><article className="card" key={n}><Art name="books-ebooks-cover-set" alt="Concept covers for the planned knowledge collection"/><div className="card-body"><span className="eyebrow">PLANNED COLLECTION</span><h3>{n}</h3><p>Accessible ideas, practical exercises and prompts for reflection. [Title and price to confirm]</p><details><summary>Read more</summary><p>Ask us about the proposed contents, sample pages and release plans for this collection.</p></details><div className="actions"><Button href={whatsapp(`Please share e-book availability, a preview and pricing for ${n}.`)}>Enquire: e-book</Button><Button href={whatsapp(`Please share printed edition availability and pricing for ${n}.`)} secondary>Printed edition</Button></div></div></article>)}</div></div></Section><Section id="knowledge-hub"><Title eyebrow="KNOWLEDGE HUB" title="Feed your curiosity."/><Gallery items={insights} kind="insights"/></Section><Section dark><div className="split"><div><Title eyebrow="KEEP LEARNING" title="A useful first step, in your inbox." text="Ask about a beginner guide and upcoming resources. We’ll confirm what’s available directly."/></div><LeadForm/></div></Section><CTA/></>}
