"use client";
import {useState} from "react";
import {Button} from "./UI";
import {whatsapp} from "@/lib/whatsapp";
export const paths=[{title:"Students",goal:"Study with clarity, curiosity and confidence.",skills:["Ask better research questions","Turn notes into revision prompts","Check explanations against your syllabus"]},{title:"Job Seekers",goal:"Bring your own story to a stronger application.",skills:["Structure a truthful resume","Prepare role-specific interview questions","Practise answers and refine your examples"]},{title:"Professionals",goal:"Make space for work that needs your judgment.",skills:["Summarise non-sensitive notes","Draft clearer presentations","Create a repeatable review checklist"]},{title:"Entrepreneurs",goal:"Move an idea toward a useful first experiment.",skills:["Explore customer needs","Compare offer ideas","Plan a small validation test"]},{title:"Self-Employed",goal:"Spend less time facing a blank page.",skills:["Outline proposals","Plan useful content","Organise follow-ups"]},{title:"Small Businesses",goal:"Connect your daily work with your growth goals.",skills:["Map repetitive tasks","Build a content calendar","Review customer questions"]},{title:"Educators",goal:"Create learning support with a human guide.",skills:["Explore lesson structures","Draft questions for review","Adapt explanations to learners"]}];
export function PersonaSelector(){const[selected,setSelected]=useState(0);return <><div className="filters" aria-label="Choose your learning path">{paths.map((p,i)=><button key={p.title} aria-pressed={selected===i} onClick={()=>setSelected(i)}>{p.title}</button>)}</div><div className="persona-panel" aria-live="polite"><span className="eyebrow">BEGINNER FRIENDLY · GUIDED PRACTICE</span><h3>{paths[selected].title}</h3><p className="large">{paths[selected].goal}</p><ul>{paths[selected].skills.map(s=><li key={s}>{s}</li>)}</ul><p>Recommended starting point: AI Foundations & Practical Prompting.</p><Button href={whatsapp(`Hi Vihaan AI Verse, I’m interested in the ${paths[selected].title} learning path.`)}>Enquire about this path</Button></div><noscript>{paths.map(p=><article key={p.title}><h3>{p.title}</h3><p>{p.goal}</p><ul>{p.skills.map(s=><li key={s}>{s}</li>)}</ul></article>)}</noscript></>}
const skills=["Prompting","Research","Productivity","Content Creation","Automation","Data Analysis","Presentations","Coding Assistance","AI Agents"];
export function Skills(){const[chosen,setChosen]=useState("Prompting");return <><div className="filters">{skills.map(s=><button key={s} aria-pressed={s===chosen} onClick={()=>setChosen(s)}>{s}</button>)}</div><p aria-live="polite"><strong>{chosen}:</strong> choose a small task, give useful context, compare the output and refine it with human review. Advanced workflows build on these foundations.</p></>}
const experiments=[{title:"A study companion",status:"Exploring",text:"A concept for turning notes into questions that encourage understanding."},{title:"A small-business content planner",status:"Prototyping",text:"An illustrative direction for connecting customer needs with a weekly content plan."},{title:"A human review checklist",status:"Testing",text:"A proposed workflow for making output review part of everyday AI use."}];
export function Lab(){const[filter,setFilter]=useState("All");return <><p>[Illustrative lab concepts and statuses — actual project progress to confirm]</p><div className="filters">{["All","Exploring","Prototyping","Testing","Building","Launched"].map(s=><button key={s} aria-pressed={filter===s} onClick={()=>setFilter(s)}>{s}</button>)}</div><div className="grid cards-grid">{experiments.filter(x=>filter==="All"||x.status===filter).map(x=><article className="card card-body" key={x.title}><span className="eyebrow">{x.status}</span><h3>{x.title}</h3><p>{x.text}</p></article>)}</div>{!experiments.some(x=>filter==="All"||x.status===filter)&&<p role="status">No confirmed projects in this stage yet. Explore the early concepts or discuss a collaboration.</p>}</>}
export function LeadForm(){return <form className="lead-form" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);window.open(whatsapp(`Hi Vihaan AI Verse, please share details about your beginner guide. My email: ${String(d.get("email"))}`),"_blank","noopener,noreferrer")}}><label>Email for your guide enquiry<input name="email" type="email" required placeholder="you@example.com"/></label><button className="button">Request guide on WhatsApp ↗</button><small>This opens an enquiry, not a newsletter subscription.</small></form>}
