function resolveSiteUrl(value:string|undefined){try{const url=new URL(value||"https://vihaanreddypendyala.com");return ["http:","https:"].includes(url.protocol)?url.origin:"https://vihaanreddypendyala.com"}catch{return "https://vihaanreddypendyala.com"}}
export const site = {name: "Vihaan AI Verse", email: "VihaanAIVerse@gmail.com", phone: "+91 9014885994", whatsapp: "919014885994", hours: "9 AM–9 PM IST", url: resolveSiteUrl(process.env.NEXT_PUBLIC_SITE_URL)};
export const nav = ["Home", "Learn AI", "Solutions", "Products", "Books & Insights", "About"];
export const navHref=(n:string)=>({"Home":"/","Learn AI":"/learn-ai","Books & Insights":"/books-insights"}[n] || `/${n.toLowerCase()}`);
export const subsections: Record<string,string[]> = {"Learn AI":["Paths","Skills","Tools","Workshops"],Solutions:["Ideate","Create","Build","Develop","Promote"],Products:["Toolkits","Templates","Prompt Packs"],"Books & Insights":["Books","Knowledge Hub"],About:["Story","Innovation Lab","Human Potential","Entrepreneurship"]};
export const slug = (s:string) => s.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/-$/," ").trim();
export const pillars = [
 {title:"AI & Digital Transformation",image:"pillar-ai-transformation",text:"Find the places where AI can make your work simpler, smarter and more useful.",anchor:"ai"},
 {title:"AI Coaching & Learning",image:"pillar-coaching",text:"Build practical capabilities you can take into your work and everyday life.",anchor:"technology"},
 {title:"Growth & Digital Marketing",image:"pillar-marketing",text:"Turn a clear story into meaningful connections with the right people.",anchor:"digital-marketing"},
 {title:"Human Potential & Wellbeing",image:"pillar-wellbeing",text:"Make room for better choices, thoughtful work and a more balanced life.",anchor:"health-wellness"}];
export const services = [
 {title:"AI Coaching & Mentorship",text:"Learn by doing, with guidance shaped around your goals and experience.",image:"offering-coaching"},
 {title:"AI & Digital Transformation Consulting",text:"Identify useful opportunities, test a focused workflow and build from what works.",image:"pillar-ai-transformation"},
 {title:"Website Design & Development",text:"Give your business a clear, compelling digital home built around your customers.",image:"offering-websites-apps"},
 {title:"App Development",text:"Turn a real user problem into a focused digital product or practical MVP.",image:"portfolio-featured-2"},
 {title:"Digital Marketing & Growth",text:"Connect strategy, content and AI to make your business easier to discover.",image:"offering-digital-marketing"},
 {title:"E-Books & Digital Guides",text:"Explore accessible ideas and practical steps you can return to as you learn.",image:"offering-ebooks"}];
export const focus = [
 {title:"AI",text:"Start with a useful question. Explore how AI can support research, planning and routine work while keeping human judgment in the loop.",steps:["Choose one task","Test a small workflow","Check the output"],image:"pillar-ai-transformation"},
 {title:"Technology",text:"Good technology makes your next step easier. I explore websites, apps and tools through the lens of usability, accessibility and real needs.",steps:["Understand the need","Build simply","Improve with feedback"],image:"offering-websites-apps"},
 {title:"Entrepreneurship",text:"An idea becomes useful when it meets a real need. Explore small experiments, clearer offers and digital products that earn their place.",steps:["Listen to people","Test the idea","Learn before scaling"],image:"offering-ebooks"},
 {title:"Digital Marketing",text:"Visibility starts with relevance. Bring your audience, story and channels together in a consistent approach to sustainable growth.",steps:["Know your audience","Create with purpose","Review what connects"],image:"pillar-marketing"},
 {title:"Creativity",text:"AI can widen the canvas. Curiosity, taste and thoughtful editing turn possibilities into work that feels distinctly human.",steps:["Explore directions","Make something","Refine with judgment"],image:"pillar-coaching"},
 {title:"Health & Wellness",text:"Being future-ready should leave room for being human. I explore mindful technology use, learning rhythms and a sustainable relationship with work.",steps:["Notice your habits","Create boundaries","Protect time to recharge"],image:"pillar-wellbeing"}];
export type Item = {title:string;category:string;image:string;text:string;body:string[];label:string};
export const projects:Item[] = [
 {title:"A clearer digital storefront",category:"Completed Work",image:"portfolio-featured-1",label:"[Sample concept · client details to confirm]",text:"A website direction built around a small business and its next customer.",body:["Concept: create a welcoming website with a clear offer, useful service information and an easy enquiry path.","This is an illustrative portfolio entry, not a claim of completed client work. [Client, scope, completion date and results to confirm]."]},
 {title:"An everyday AI companion",category:"Projects",image:"portfolio-featured-2",label:"[Sample project · status to confirm]",text:"Exploring a focused app that helps turn a task into a practical next step.",body:["Concept: a simple interface for capturing a task, considering options and choosing a useful action.","[Project owner, development status, features and outcomes to confirm]."]},
 {title:"From prompt to possibility",category:"Experiments",image:"offering-coaching",label:"[Illustrative experiment]",text:"A learning concept for comparing AI suggestions with human judgment.",body:["Try the same task with different context, constraints and examples. Compare what becomes more useful and what still needs checking.","This describes an experiment idea, not a published research result. [Actual experiment details to confirm]."]},
 {title:"The practical AI field guide",category:"Ideas in Development",image:"offering-ebooks",label:"[Concept · availability to confirm]",text:"An accessible guide concept for learning, applying and reflecting.",body:["Proposed chapters explore task selection, giving useful context and reviewing outputs with care.","[Title, release date, contents and pricing to confirm]."]}];
export const insights:Item[] = [
 {title:"Start with a task. Not a tool.",category:"Articles",image:"pillar-ai-transformation",label:"3 min read",text:"A practical starting point for bringing AI into your everyday work.",body:["Before choosing another tool, choose one task you would like to make easier. It might be outlining a proposal, organising notes or exploring content ideas. Write down what a useful result would look like.","Give the AI context: who the work is for, what you already know and what constraints matter. Ask for a first draft, then examine it. Are the facts reliable? Is anything missing? Does it sound like you?", "Repeat on a small, low-risk task. Compare the time and attention it takes with your usual process. Keep the workflow only if it helps. Practical AI starts with a clear purpose and ends with your judgment."]},
 {title:"Your judgment is part of the workflow",category:"Tutorials",image:"belief-section-bg",label:"2 min read",text:"Why a useful first draft still needs a thoughtful second look.",body:["Fluent writing can sound more certain than it deserves. Treat an AI output as a proposal to review, not a conclusion to accept.","Check claims against sources you trust. Look for missing context and assumptions. Edit for the person who will actually use the work.","Your experience, empathy and understanding of the situation are valuable inputs. Build a review step into the workflow from the beginning."]},
 {title:"A better prompt begins with context",category:"AI Discoveries",image:"pillar-coaching",label:"2 min read",text:"Explore how audience, constraints and examples change the conversation.",body:["Try a small comparison: ask for a generic explanation, then ask again with an audience, a purpose and a desired format. Notice where the response becomes easier to use.","For example: explain an idea to a first-time business owner, give one practical example, and list questions that need more information. You can add a sample of the style you prefer.","Specificity helps you evaluate the result. It does not guarantee accuracy, so keep checking important details."]},
 {title:"Make space for the human part",category:"Quick Learnings",image:"pillar-wellbeing",label:"2 min read",text:"Capability matters. So does the life you are building around it.",body:["Doing more is not the only reason to use technology. A useful tool might give you a calmer start, time to learn or space for a better conversation.","Choose boundaries deliberately. Leave room to think without a screen, to ask your own questions and to work at a pace you can sustain.","Human-Augmented Intelligence begins with human priorities: curiosity, creativity, empathy and purpose."]}];
export const faqs = [
 ["What exactly do you help with?","We help individuals and businesses use AI practically through coaching, digital transformation, websites, apps, marketing and digital guides."],
 ["Do I need to already know AI?","No prior AI knowledge is needed. We can start with your goals, your current skills and one useful task."],
 ["How does coaching work?","Coaching is shaped around your goals. [Format, duration and pricing to be confirmed]. Reach out to discuss a suitable starting point."],
 ["Can you build a website or app for my business?","Yes. Website and app development are core offerings. [Project scope, turnaround time and pricing to be confirmed after discussion]."],
 ["Do you work with individuals as well as businesses?","Both. Students, freelancers and job seekers can explore coaching and learning; businesses can discuss digital products, transformation and marketing."],
 ["How do I get started?","Send a WhatsApp message or an email with a little about your goal. Our contact hours are 9 AM–9 PM IST."],
 ["Where can I find your credentials?","[Certifications and credentials to confirm]. The About page keeps these details clearly marked until verified."]];

insights.push({title:"Your first AI workflow checklist",category:"Guides & Downloads",image:"apply-ai-productivity",label:"PRACTICAL CHECKLIST",text:"A simple checklist for choosing and reviewing one useful AI task.",body:["1. Choose a low-risk task with a clear outcome. 2. Remove personal or confidential information. 3. Add audience, context and constraints. 4. Check facts and assumptions. 5. Edit the result in your own voice. 6. Decide whether the workflow actually helped.","Copy this checklist into your notes and adapt it to your work. A downloadable edition is available by enquiry, subject to confirmation."]});
